### ISSUE TITLE
results table <a> links aren't working

### ISSUE THREAD

**Issue by falon3** [jose-lpa/django-tracking-analyzer#14]
the imbedded object links in the table of results aren't being coded properly:
![image](https://user-images.githubusercontent.com/9426758/68513124-7786c800-0237-11ea-932d-89dbc421002b.png)

This may be related to why the filters on the side by content-type also aren't working (always filters to  no results even when there is at least one)

**Comment by tnory56** [comment]
Fix #15 should do the trick.

**Comment by falon3** [comment]
yes this is better now, thanks
