### ISSUE TITLE
Crashes with certain user agent strings

### ISSUE THREAD

**Issue by owenh000** [jose-lpa/django-tracking-analyzer#17]
Certain user agent strings, such as `xxxxxxxxxxxxxxxxxxxxxxxxxxxxbot`, crash this app, causing a 500 error for the visitor. Tested with version 1.0.2.

1. The example string is parsed by [python-user-agents](https://github.com/selwin/python-user-agents) as a browser family string that is longer than 30 characters.
2. A Tracker object is created using that string for the `browser` field.
3. A `DataError: value too long for type character varying(30)` exception is raised.

**Comment by jose-lpa** [comment]
This should have been fixed in PR #24 :+1:
