### ISSUE TITLE
'WSGIRequest' object has no attribute 'user_agent'

### ISSUE THREAD

**Issue by mav-erick** [jose-lpa/django-tracking-analyzer#4]
Error in django 1.11. Please help.

 ` if request.user_agent.is_mobile: `

**Comment by cvarelaruiz** [comment]
You need to ensure that [Django User Agents](https://github.com/selwin/django-user_agents) is installed. Then you need to add it to the INSTALL_APPS section in your django config file as well as the 'django_user_agents.middleware.UserAgentMiddleware' to the MIDDLEWARE section (or MIDDLEWARE_CLASSES depending on your version of django) .
